version: "3.9"

services:
  dummy:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE_NAME: dummy
    image: services_dummy:latest
    ports:
      - 3000:3000
    networks:
      - shared_network
networks:
  shared_network:
    external: true
